---
title: "Method"
output:
  html_document:
    df_print: paged
editor_options:
  markdown:
    wrap: 72
---

## Analysis

The majority of the raw data is composed of features with the character
data type whilst others are numeric features. Some categorical features
such as `country`, `state_prov` and `city` contain information relating
to the origin of the pumpkin and where it was grown. Others numeric
features such as `year` stores which year the pumpkin was grown and
`ott` is the "over-the-top" measurement of the giant pumpkin size. We
have chosen features that we believe they may impact the weight of a
pumpkin whilst dropping other features that we deem irrelevant. We do
think `seed_mother`, and `pollinator_father` features contain genetic
information which would have an impact on the pumpkin size. However, the
data quality in these two features are low as a fairly high percentage
of data do not conform with the convention suggested (' weight seed
year') and we are not able to extract the genetic information we want,
thus we decided to drop these features.

An initial data cleaning, preparation and pre-processing was required to
ready the data for training purposes. The dataset was split with a 70/30
split for the training and test sets respectively along with random
seeding for reproducibility.

For the numeric features, we used a simple imputer to insert the 'mean'
value for any missing or Null values as well as a standard scaler via a
pipeline. For categorical features, we similarly used a simple imputer
but instead of filling in values with the mean, we filled them in with
the value 'missing'. We then used one hot encoding to encode the
categorical features.

The Ridge model was used to build and predict the weight (lbs) of a
giant pumpkin given certain features from the dataset. The model was
created using the train dataset, combined with the features we spoke
about earlier, and the actual given weights of particular giant
pumpkins.

Cross-validation is carried out to for hyperparameter tuning. We have
used the `GridSearchCV` to find the optimized value of `alpha` in the
Ridge model.
